##########################################################################
# this script was generated by openmm-builder. to customize it further,
# you can save the file to disk and edit it with your favorite editor.
##########################################################################

from __future__ import print_function
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
from sys import stdout
from datetime import datetime


T_Start=300*unit.kelvin
T_End=300*unit.kelvin
T_Steps=100
T_Delta=(T_End-T_Start)/T_Steps

sim_steps=400
output_steps=4



print ('Loading Force Field')
forcefield = app.ForceField('amoebaSmallOrg.xml','amoebaSmall.xml')

print ('Loading PDB')
pdb = app.PDBFile('SucroseBox.pdb')


print ('setting up system')
system = forcefield.createSystem(pdb.topology,
    nonbondedMethod=app.NoCutoff, constraints=None, rigidWater=False)
integrator = mm.LangevinIntegrator(T_Start, 1.0/unit.picoseconds, 
    0.5*unit.femtoseconds)
#system.addForce(mm.MonteCarloBarostat(1*unit.atmospheres, 200*unit.kelvin))

print ('Setting Platform to CUDA')
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaPrecision': 'mixed'}
simulation = app.Simulation(pdb.topology, system, integrator, platform,
    properties)
simulation.context.setPositions(pdb.positions)

print('Minimizing...')
simulation.minimizeEnergy(maxIterations=1000)

app.PDBFile.writeFile(simulation.topology, pdb.positions, open('Sucrose.minimize.pdb', 'w'))

simulation.context.setVelocitiesToTemperature(T_Start)
print('Equilibrating... Be patient, its a virtue')
simulation.step(400)
#Output PDB file
app.PDBFile.writeFile(simulation.topology, pdb.positions, open('SucroseBoxMove.pdb', 'w'))

#Output DCD file name
simulation.reporters.append(app.DCDReporter('SucroseBoxMove.dcd', output_steps))
#simulation.reporters.append(app.PDBReporter('waterSphere_trajectory.pdb', output_steps))
simulation.reporters.append(app.StateDataReporter('SucroseBox.log', output_steps, step=True,
    time=True, potentialEnergy=True, kineticEnergy=True, totalEnergy=True, 
    temperature=True, volume=True, density=True, progress=True, 
    remainingTime=True, speed=True, totalSteps=((T_Steps+1)*sim_steps), separator='\t'))

print('Running Temperature Variation...')
                  
for i in range(T_Steps):
    print("Set Temp: ", T_Start+i*T_Delta)
    integrator.setTemperature(T_Start+i*T_Delta)
    simulation.step(sim_steps)
print('Done!')
End=datetime.now()
print ('%s %s/%s/%s %s:%s:%s' %("Simulation ended at", End.month, End.day, End.year, End.hour, End.minute, End.second))
